### ISSUE TITLE
Build gets: No resource found for [material].

### ISSUE THREAD

**Issue by FrancoisMongeau** [ovasquez/docfx-material#4]
When I build, I get:

`Warning:[ExportResourceFiles]No resource found for [material].`

When you write "Create a templates folder in the root of your DocFX directory", where exactly is this? In the DocFX folder where folders 'tools', 'build' and 'content' are? That is where I created the template folder and copied your template folder.

`docfx 2.56.2.0`

Thanks

**Comment by ovasquez** [comment]
Hi @FrancoisMongeau, the docfx folder is the one where you have your markdown files and the `docfx.json` for your documentation site.

You have to reference the `material` folder from your `docfx.json`, here's how I referenced it [on this github repo.](https://github.com/ovasquez/docfx-material/blob/master/docs/docfx.json#L28).

Does this answer your question?

**Comment by ovasquez** [comment]
I'm closing this since it seems to be a non-issue, and there was no response.
