### ISSUE TITLE
Need to adjust the width of main content 

### ISSUE THREAD

**Issue by prashantSinghRana** [ovasquez/docfx-material#9]
Need to move "In this Article" to extreme right to reduce white space and provide more width to content body
![image](https://user-images.githubusercontent.com/73402083/100843325-33004700-34a0-11eb-95c8-31fe302d328a.png)

**Comment by ovasquez** [comment]
Hi @prashantSinghRana, this repository is only for the material theme, I would suggest that you ask in the official [repository of DocFX](https://github.com/dotnet/docfx), or a related web forum.

Since this is not related to the material theme, I'm closing this issue.
